excluded:
  - .build
  - Build
  - Carthage
  - DerivedData
  - Pods

analyzer_rules:
  - unused_import

disabled_rules:
  - block_based_kvo
  - closure_body_length
  - computed_accessors_order
  - cyclomatic_complexity
  - duplicate_imports
  - empty_enum_arguments
  - empty_string
  - file_length
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - identifier_name
  - implicit_getter
  - implicitly_unwrapped_optional
  - indentation_width
  - large_tuple
  - legacy_objc_type
  - line_length
  - multiple_closures_with_trailing_closure
  - nesting
  - orphaned_doc_comment
  - operator_whitespace
  - return_arrow_whitespace
  - shorthand_operator
  - todo
  - trailing_closure
  - type_body_length
  - type_name
  - unneeded_break_in_switch
  - unused_optional_binding
  - vertical_parameter_alignment
  - xctfail_message

opt_in_rules:
  - closure_body_length
  - empty_string
  - fallthrough
  - force_unwrapping
  - implicitly_unwrapped_optional
  - indentation_width
  - legacy_objc_type
  - override_in_extension
  - redundant_nil_coalescing
  - static_operator
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - weak_delegate

custom_rules:
  commented_out_code:
    included: .*\.swift # regex that defines paths to include during linting. optional.
    excluded: .*Test(s)?\.swift # regex that defines paths to exclude during linting. optional
    name: Commented out code # rule name. optional.
    regex: ^\s*(\/\/(?!\s*swiftlint:).*|\/\*[\s\S]*?\*\/) # matching pattern
    capture_group: 0 # number of regex capture group to highlight the rule violation at. optional.
    match_kinds: # SyntaxKinds to match. optional.
      - comment
    message: No commented code in devel branch allowed. # violation message. optional.
    severity: warning # violation severity. optional.
